services:
  frontend:
    image: ghcr.io/steffenburgert/frontend:0.0.1-snapshot-aoc-infra
    container_name: aoc
    restart: unless-stopped
    deploy:
      replicas: 1

  backend:
    image: ghcr.io/steffenburgert/backend:0.0.1-snapshot-aoc-infra
    container_name: aoc
    restart: unless-stopped
    deploy:
      replicas: 1
