services:
  frontend:
    image: ghcr.io/steffenburgert/frontend:0.0.1-snapshot-aoc-infra
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 250M
      replicas: 1

  backend:
    image: ghcr.io/steffenburgert/backend:0.0.1-snapshot-aoc-infra
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 250M
      replicas: 1
