services:
  frontend:
    image: registry.simpletactics.de/sitafrontend:2026-02-14.160
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 250M
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - main

  backend:
    image: registry.simpletactics.de/sitabackend:2026-02-09.133
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 250M
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure
    environment:
      - TZ=Europe/Berlin
    networks:
      - main
    secrets:
      - DB_USERNAME
      - DB_PASSWORD
      - SITA_BOT_ALERTING_URL
      - source: DB_CONNECTION_STRING_DEV
        target: DB_CONNECTION_STRING
        mode: 0400
      - source: SITA_BOT_ALERTING_CHANNEL_ID_DEV
        target: SITA_BOT_ALERTING_CHANNEL_ID
        mode: 0400

  socket:
    image: registry.simpletactics.de/sitasocket:1.0.0
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - main

networks:
  main:
    external: true

secrets:
  DB_USERNAME:
    external: true
  DB_PASSWORD:
    external: true
  DB_CONNECTION_STRING_DEV:
    external: true
  SITA_BOT_ALERTING_URL:
    external: true
  SITA_BOT_ALERTING_CHANNEL_ID_DEV:
    external: true
